config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :boards do
    resources :tasks
  end
  root 'boards#index'
end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :user
  has_many :tasks
  validates :title, presence: true
  validates :user_id, presence: true, unless: "public?"
  
  # Scope
  scope :all_public, -> { where(public: true) }
  scope :all_private, -> { where(public: false) }
  scope :by_user_and_private, -> (user) { where(user_id: user, public: false) }
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  belongs_to :board
  validates :title, :board_id, presence: true
  enum status: [ :to_do, :in_progress, :to_verify, :done ]
  enum priority: [ :low, :normal, :high ]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :boards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]
  def index
    @boards = Board.all_public
    @boards += Board.by_user_and_private(current_user) if user_signed_in?
  end

  def new
    @board = Board.new
  end

  def show
  end

  def create
    @board = Board.new(board_params)
    @board.user = current_user if user_signed_in?
    
    if @board.save
      redirect_to @board, notice: 'Board created successfully!'
    else
      render :new
    end
    
  end
  
  def destroy
    @board.destroy
    redirect_to boards_url, notice: 'Board deleted successfully!'
  end

  private
    def set_user
      
    end

    def set_board
      @board = Board.find(params[:id])
    end

    def board_params
      params.require(:board).permit(:title, :public, :user_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_board
  
  def index
    @tasks = @board.tasks
  end
  
  def new
    @task = Task.new
  end
  
  def create
    @task = @board.tasks.new(task_params)
    @task.user = current_user if user_signed_in?
    
    respond_to do |format|
      if @task.save
        format.html { redirect_to @board, notice: 'Task created successfully!' }
        format.js { render json: @task, status: :created }
      else
        format.html { render 'new' }
        format.js { render json: @task.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end
  
  private
    def set_board
      @board = Board.find(params[:board_id])
    end
    
    def task_params
      params.require(:task).permit(:title, :user_id, :priority, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_form.html.erb
<%= form_for @board, html: { class: "form-group" } do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <div class="checkbox">
      <label>
        <%= f.check_box :public %>
        Quadro público
    </label>
    </div>
  </div>
  <div class="form-group">
    <%= f.submit "Salvar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/boards/index.html.erb
<div class="row">
  <% @boards.each do |board| %>
    <div class="col-sm-6 col-md-4 col-lg-3">
      <div class="panel panel-info">
        <div class="panel-heading">
          <%= link_to board.title, board_path(board), class: "panel-title" %>
          <%= link_to board_path(board), method: :delete, remote: true, data: {confirm: 'Certeza que deseja deletar ?' } do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </div>
        <div class="panel-body">
          <%= board.title %>
        </div>
        <div class="panel-footer small">
          <footer class="text-right">
              <% unless board.public? %>
                <span class="glyphicon glyphicon-lock"></span>
              <% end %>
              <%= board.user.nil? ? "-" : board.user.email %>
          </footer>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/boards/new.html.erb
<div class="row">
  <div class="col-xs-6">
    <h2>Novo quadro de tarefas</h2>
  </div>
</div>
<div class="row">
  <div class="col-xs-6">
    <%= render 'form' %>
  </div>
</div>

app/views/boards/show.html.erb
<% content_for :board_content do %>
    <p class="navbar-text"><%= @board.title %></p>
    <button type="button" class="btn btn-default glyphicon glyphicon-plus" data-toggle="modal" data-target="#newTask" />
<% end %>

<div class="row heading">
  <% Task.statuses.each do |status| %>
    <div class="col-xs-3">
      <h2><%= status[0].to_s.underscore.humanize %></h2>
    </div>
  <% end %>
</div>

<div class="row lanes">
  <% Task.statuses.keys.each do |status| %>
    <div class="lane col-xs-3 <%= status %>">
      <% @board.tasks.send(status.to_s).each do |task| %>
        <%= render task %>
      <% end %>
    </div>
  <% end %>
</div>

<div class="modal fade" id="newTask" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="newTaskLabel">Nova tarefa</h4>
      </div>
        
      <div class="modal-body">
        <%= render 'tasks/form', modal: true %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <a class="close" data-dismiss="alert">&#215;</a>
      O formulário contém <%= pluralize(object.errors.count, "erro") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <!-- <li><%#= msg %></li> -->
      <%= content_tag :li, msg, :id => "error_#{msg}" if msg.is_a?(String) %>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Home", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "Novo", new_board_path %>
        </li>
        <%= yield :board_content %>
      </ul>
      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
          <p class="navbar-text"><%= current_user.email %></p>
          <%= link_to "Logout", destroy_user_session_path, class: "btn btn-default navbar-btn navbar-right", method: :delete %>
        <% else %>
          <%= link_to "Login", new_user_session_path, class: "btn btn-default navbar-btn navbar-right" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>RockBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/nav' %>
  <div class="container-fluid">
    <p id="notice"><%= notice %></p>
    <%= yield %>
  </div>

</body>
</html>

app/views/tasks/_form.html.erb
<% modal ||= false %>
<% remote = modal ? true : false %>

<%= form_for [@board, Task.new] , method: :post, remote: remote, html: { class: "form-group" } do |f| %>
  <div id="error_explanation">
  </div>
  
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :priority %>
    <%= f.select(:priority) do %>
      <% Task.priorities.keys.each_with_index do |value, index| %>
        <%= content_tag(:option, value.humanize, value: value) %>
      <% end %>
    <% end %>
    <%= f.label :status %>
    <%= f.select(:status) do %>
      <% Task.statuses.keys.each_with_index do |value, index| %>
        <%= content_tag(:option, value.to_s.underscore.humanize, value: value) %>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.submit "Salvar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="task">
  <div class="media">
    <div class="task-body">
      <h4><%= task.title %></h4>
      <div class="row">
        <div class="col-xs-6">
          <span><b>Status: </b><%= task.status.underscore.humanize %></span>
        </div>
        <div class="col-xs-6 text-right">
          <span><b>Prioridade: </b><%= task.priority.underscore.humanize %></span>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="row">
  <div class="col-lg-6">
    <h2>Nova tarefa em <%= @board.title %></h2>
  </div>
</div>
<div class="row">
  <div class="col-lg-6">
    <%= render 'form' %>
  </div>
</div>